TrueLayer/truelayer-java

build.gradle
gradle.properties
src/main/java/com/truelayer/java/ConnectionPoolOptions.java
src/main/java/com/truelayer/java/TrueLayerClientBuilder.java
src/test/java/com/truelayer/java/TestUtils.java
src/test/java/com/truelayer/java/acceptance/AcceptanceTests.java
src/test/java/com/truelayer/java/integration/TimeoutIntegrationTests.java

Please include a sufficiently detailed description of your changes
Improves the configurability of the client WRT: 
- HTTP call timeout
- HTTP connection pool
- HTTP requests dispatcher

[JSDK-74] Improved configurability: call timeout, connection pool and request dispatcher

---

README.md
gradle/wrapper/gradle-wrapper.properties

Added documentation to help M1 users build the project with Java up to 18
- [] My code follows the style guidelines of this project

[skip ci] Updated Gradle wrapper version to support Java 18, documented M1

---

.github/workflows/release-snapshot.yml
gradle.properties
src/main/java/com/truelayer/java/TrueLayerClientBuilder.java
src/main/java/com/truelayer/java/http/OkHttpClientFactory.java
src/test/java/com/truelayer/java/http/OkHttpClientFactoryTests.java

Aimed to improve testability of the client builder. 
- [] I have updated the relevant documentation

[JSDK-77] Client builder refactor for testability

---

examples/quarkus-mvc/README.md
examples/quarkus-mvc/src/main/java/com/truelayer/quarkusmvc/TrueLayerClientProvider.java

Minor improvements to our sample app docs.

[JSDK-83] Sample app documentation improvement

---

gradle.properties
src/main/java/com/truelayer/java/entities/providerselection/ProviderSelection.java
src/main/java/com/truelayer/java/entities/providerselection/UserSelectedProviderSelection.java
src/main/java/com/truelayer/java/mandates/entities/mandatedetail/MandateDetail.java
src/main/java/com/truelayer/java/payments/entities/providerselection/PreselectedProviderSelection.java
src/test/resources/__files/mandates/200.get_mandate_by_id.authorized.json
src/test/resources/__files/mandates/200.get_mandate_by_id.authorizing.json
src/test/resources/__files/mandates/200.get_mandate_by_id.revoked.json
src/test/resources/__files/payments/200.get_payment_by_id.authorized.json
src/test/resources/__files/payments/200.get_payment_by_id.authorizing.json
src/test/resources/__files/payments/200.get_payment_by_id.executed.json

Onboards [this api specs PR ](https://github.com/TrueLayer/payments-api-openapi-specs/pull/171)

[REC-567] `provider_selection` object on mandate detail DTO

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/mandates/entities/mandatedetail/AuthorizedMandateDetail.java
src/main/java/com/truelayer/java/mandates/entities/mandatedetail/RevokedMandateDetail.java
src/test/resources/__files/mandates/200.get_mandate_by_id.authorized.json
src/test/resources/__files/mandates/200.get_mandate_by_id.revoked.json

Please include a sufficiently detailed description of your changes
This includes the latest update to our API. We now return the Remitter object for Authorised and Revoked mandates, even for user-selected bank accounts.

[REC-550] Update SDK with new Remitter field

---

build.gradle
gradle.properties

Please include a sufficiently detailed description of your changes
[Fixes # (issue)]

Bump signing library

---

build.gradle
examples/quarkus-mvc/build.gradle
gradle.properties

Please include a sufficiently detailed description of your changes
[Fixes # (issue)]

dependencies updates

---

src/main/java/com/truelayer/java/ITrueLayerClient.java
src/main/java/com/truelayer/java/TrueLayerClient.java
src/main/java/com/truelayer/java/TrueLayerClientBuilder.java
src/main/java/com/truelayer/java/http/OkHttpClientFactory.java
src/main/java/com/truelayer/java/paymentsproviders/IPaymentsProvidersApi.java
src/main/java/com/truelayer/java/paymentsproviders/IPaymentsProvidersHandler.java
src/main/java/com/truelayer/java/paymentsproviders/PaymentsProvidersHandler.java
src/main/java/com/truelayer/java/paymentsproviders/PaymentsProvidersHandlerBuilder.java
src/main/java/com/truelayer/java/paymentsproviders/entities/BankTransferCapabilities.java
src/main/java/com/truelayer/java/paymentsproviders/entities/Capabilities.java
src/main/java/com/truelayer/java/paymentsproviders/entities/MandatesCapabilities.java
src/main/java/com/truelayer/java/paymentsproviders/entities/PaymentsCapabilities.java
src/main/java/com/truelayer/java/paymentsproviders/entities/PaymentsProvider.java
src/main/java/com/truelayer/java/paymentsproviders/entities/Scheme.java
src/main/java/com/truelayer/java/paymentsproviders/entities/VrpCommercialCapabilities.java
src/main/java/com/truelayer/java/paymentsproviders/entities/VrpSweepingCapabilities.java
src/test/java/com/truelayer/java/TestUtils.java
src/test/java/com/truelayer/java/acceptance/PaymentsProvidersAcceptanceTests.java
src/test/java/com/truelayer/java/http/OkHttpClientFactoryTests.java
src/test/java/com/truelayer/java/integration/MandatesIntegrationTests.java
src/test/java/com/truelayer/java/integration/PaymentsIntegrationTests.java
src/test/java/com/truelayer/java/integration/PaymentsProvidersIntegrationTests.java
src/test/resources/__files/payments_providers/200.get_payments_provider.json

Adds support for the `GET /payments-providers/{id}` endpoint.

feat: [JSDK-70] get payments provider endpoint

---

gradle.properties

Version bump for the previous PR to release a new version.

fix: upgraded version to 2.5.0

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/paymentmethod/Mandate.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/payments/entities/paymentmethod/PaymentMethodTests.java

Adds support for setting a reference on payments on VRP mandates, as per our public docs.

[REC-718] feat(recurring payments): reference added to create payment request for mandates

---

gradle.properties
src/main/java/com/truelayer/java/Constants.java
src/main/java/com/truelayer/java/http/interceptors/UserAgentInterceptor.java
src/test/java/com/truelayer/java/TestUtils.java
src/test/java/com/truelayer/java/http/interceptors/UserAgentInterceptorTests.java
src/test/java/com/truelayer/java/http/interceptors/logging/SensitiveHeaderGuardTests.java

Implementing the TL-Agent management as defined by the _recently_ updated SDK standards.
[Fixes # (issue)]

[EWT-61] feat(observability): User-agent HTTP header replaced with TL-Agent

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/entities/providerselection/ProviderSelection.java
src/main/java/com/truelayer/java/entities/providerselection/UserSelectedProviderSelection.java
src/main/java/com/truelayer/java/http/OkHttpClientFactory.java
src/main/java/com/truelayer/java/http/interceptors/TrueLayerAgentInterceptor.java
src/main/java/com/truelayer/java/mandates/entities/beneficiary/Beneficiary.java
src/main/java/com/truelayer/java/mandates/entities/providerselection/PreselectedProviderSelection.java
src/main/java/com/truelayer/java/payments/entities/AuthorizationFlowResponse.java
src/main/java/com/truelayer/java/payments/entities/CreatePaymentResponse.java
src/main/java/com/truelayer/java/payments/entities/beneficiary/Beneficiary.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/AuthorizationFlowAction.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/PaymentDetail.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/RedirectStatus.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/forminput/Input.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/forminput/image/Image.java
src/main/java/com/truelayer/java/payments/entities/paymentmethod/PaymentMethod.java
src/main/java/com/truelayer/java/payments/entities/providerselection/PreselectedProviderSelection.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/java/com/truelayer/java/http/OkHttpClientFactoryTests.java
src/test/java/com/truelayer/java/http/interceptors/TrueLayerAgentInterceptorTests.java
src/test/java/com/truelayer/java/http/interceptors/UserAgentInterceptorTests.java

Mostly a tech debt PR with a few getters additions to help with responses evaluation. There were a few issues with serializations which I stumbled across during last hackathon and this PR aims to fix those as well. 

[JSDK-86] New getters to help with responses interpretations + Dependency updates

---

gradle.properties
src/main/java/com/truelayer/java/mandates/IMandatesApi.java
src/main/java/com/truelayer/java/mandates/IMandatesHandler.java
src/main/java/com/truelayer/java/mandates/MandatesHandler.java
src/main/java/com/truelayer/java/mandates/entities/GetConstraintsResponse.java
src/main/java/com/truelayer/java/mandates/entities/PeriodicLimit.java
src/main/java/com/truelayer/java/mandates/entities/PeriodicLimitDetail.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/integration/MandatesIntegrationTests.java
src/test/java/com/truelayer/java/mandates/MandatesHandlerTests.java
src/test/resources/__files/mandates/200.get_constraints.json

This PR adds the GetConstraints call as documented [here](https://docs.truelayer.com/reference/get-constraints) to the SDK. 

[REC-740] Get Mandate Constraints + tests

---

build.gradle
gradle.properties

Reviewing the declaration of transitive dependencies as suggested on Gradle's official doc. This way we can also specify why we're requesting a specific version

transitive dependencies constraint block to replace previous direct dependencies

---

gradle.properties
src/main/java/com/truelayer/java/entities/CurrencyCode.java
src/main/java/com/truelayer/java/payments/entities/CountryCode.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java

Adds support for the currencies `PLN` and `NOK`.
Also adds missing supported country codes.

feat: [PAYG-1363] add PLN and NOK currencies

---

gradle.properties
src/main/java/com/truelayer/java/entities/AvailabilityRecommendedStatus.java
src/main/java/com/truelayer/java/entities/Provider.java
src/main/java/com/truelayer/java/entities/ProviderAvailability.java
src/main/java/com/truelayer/java/mandates/entities/mandatedetail/FailedMandateDetail.java
src/main/java/com/truelayer/java/mandates/entities/mandatedetail/RevokedMandateDetail.java
src/test/resources/__files/mandates/200.get_mandate_by_id.revoked.json
src/test/resources/__files/mandates/200.start_authorization_flow.authorizing.provider_selection.json
src/test/resources/__files/payments/200.start_authorization_flow.authorizing.provider_selection.json

Fix some payments and mandates models inconsistencies (for more info see [the Jira ticket](https://truelayer.atlassian.net/browse/EWT-306))
[Fixes # (issue)]

[EWT-306] Fix models inconsistencies

---

.github/workflows/acceptance-tests.yml
.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/release-final.yml
.github/workflows/release-snapshot.yml

This PR is about building also against the latest available JDK version (20).
As part of these changes, I'm switching to the [Eclipse Temurin](https://adoptium.net/temurin/releases/) distribution as suggested [here](https://github.com/actions/setup-java#supported-distributions).
I won't create a release for this change.

[EWT-278] Build also against JDK 20

---

gradle.properties
src/main/java/com/truelayer/java/merchantaccounts/MerchantAccountsHandler.java
src/test/java/com/truelayer/java/acceptance/MerchantAccountsAcceptanceTests.java
src/test/java/com/truelayer/java/merchantaccounts/MerchantAccountsHandlerTests.java

Fixes a datetime formatting issue we had on the merchant account transactions endpoint.
Fixes #215

fix(EWT-328): improperly formatted datetime string on transactions endpoint

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/CreatePaymentRequest.java
src/main/java/com/truelayer/java/payments/entities/RiskAssessment.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java

Add `risk_assessment` field to create payment request

[ACL-161] Add risk_assessment field to create payment request

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/schemeselection/preselected/SchemeSelection.java
src/main/java/com/truelayer/java/payments/entities/schemeselection/preselected/UserSelectedSchemeSelection.java
src/main/java/com/truelayer/java/payments/entities/schemeselection/userselected/SchemeSelection.java
src/main/java/com/truelayer/java/payments/entities/schemeselection/userselected/UserSelectedSchemeSelection.java
src/test/java/com/truelayer/java/payments/entities/schemeselection/preselected/SchemeSelectionTests.java
src/test/java/com/truelayer/java/payments/entities/schemeselection/userselected/SchemeSelectionTests.java

Add `user_selected` scheme selection type

[ACL-159] Add user_selected scheme selection

---

gradle.properties
src/main/java/com/truelayer/java/merchantaccounts/IMerchantAccountsApi.java
src/main/java/com/truelayer/java/payments/IPaymentsApi.java
src/main/java/com/truelayer/java/payments/IPaymentsHandler.java
src/main/java/com/truelayer/java/payments/PaymentsHandler.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/java/com/truelayer/java/integration/PaymentsIntegrationTests.java

Adds support for cancelling a payment.

feat(ACL-195): Adds cancel payment support

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/Environment.java
src/test/java/com/truelayer/java/EnvironmentTests.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java

Routes payments request to /v3 prefixed endpoints by default

chore(ACL-225): v3 endpoints used for Payments API
