gradle.properties
src/main/java/com/truelayer/java/Utils.java
src/main/java/com/truelayer/java/http/entities/ProblemDetails.java
src/main/java/com/truelayer/java/http/mappers/ErrorMapper.java
src/test/java/com/truelayer/java/UtilsTests.java
src/test/java/com/truelayer/java/http/entities/ProblemDetailsTests.java
src/test/resources/__files/payments/200.get_payment_by_id.unknown_response_field.json

As per the current configuration an unknown (new) field in any of the API responses will lead to deserialization issue. 
As agreed with @tl-ozum-safaoglu this is too pedantic, therefore we're globally disabling this behavior on the SDK. 
The current setup was mostly meant to help us spot discrepancies between the expected and actual output of the APIs but we'll get the same control with other specific tools and processes in future. 

[JSDK-61] Adds support for unknown properties on response DTOs

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/payments/entities/paymentmethod/provider/PreselectedProviderSelection.java
src/main/java/com/truelayer/java/payments/entities/paymentmethod/provider/ProviderSelection.java
src/main/java/com/truelayer/java/payments/entities/paymentmethod/provider/UserSelectedProviderSelection.java
src/test/resources/__files/payments/200.get_payment_by_id.settled.json

Adds provider id and scheme id support on GET Payment response objects. 
Relates to [PAYG-726]
[PAYG-726]: https://truelayer.atlassian.net/browse/PAYG-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JSDK-62] Provider id and scheme id added in GET payment response

---

build.gradle
gradle.properties

1. Dependabot was not able to operate on versions declared on the gradle.properties file. So I changed that based on this comment
2. Bumping jackson-databind to fix [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518)

Dependabot and CVE-2020-36518 resolution

---

examples/quarkus-mvc/build.gradle
examples/quarkus-mvc/src/main/java/com/truelayer/quarkusmvc/services/DonationService.java
gradle.properties
src/main/java/com/truelayer/java/entities/accountidentifier/AccountIdentifier.java
src/test/java/com/truelayer/java/entities/accountidentifier/AccountIdentifierTests.java
src/test/java/com/truelayer/java/merchantaccounts/entities/transactions/TransactionTests.java

Solves a serialization issue introduced with version `0.7.4`

[JSDK-66] Bugfix serialization issue

---

.github/workflows/acceptance-tests.yml
.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/release-final.yml
.github/workflows/release-snapshot.yml
README.md
gradle.properties

- Adds gradle options to have spotless happy on JDK 16+. 
- Adds a matrix of JDK versions 8,11,15,17 when building the project, and updates the main one to 17
- A few doc fixes
This change won't trigger any release 

[JSDK-72] Fixes spotless on recent java version and enable CI matrix on build jobs

---

gradle.properties
src/main/java/com/truelayer/java/mandates/entities/CreateMandateRequest.java
src/main/java/com/truelayer/java/mandates/entities/mandatedetail/MandateDetail.java
src/main/java/com/truelayer/java/payments/entities/CreatePaymentRequest.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/PaymentDetail.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/resources/__files/mandates/200.get_mandate_by_id.authorization_required.json
src/test/resources/__files/mandates/200.get_mandate_by_id.authorized.json
src/test/resources/__files/mandates/200.get_mandate_by_id.authorizing.json
src/test/resources/__files/mandates/200.get_mandate_by_id.failed.json
src/test/resources/__files/mandates/200.get_mandate_by_id.revoked.json
src/test/resources/__files/mandates/200.list_mandates.json
src/test/resources/__files/payments/200.get_payment_by_id.authorization_required.json
src/test/resources/__files/payments/200.get_payment_by_id.authorized.json
src/test/resources/__files/payments/200.get_payment_by_id.authorizing.json
src/test/resources/__files/payments/200.get_payment_by_id.executed.json
src/test/resources/__files/payments/200.get_payment_by_id.failed.json
src/test/resources/__files/payments/200.get_payment_by_id.settled.json
src/test/resources/__files/payments/200.get_payment_by_id.unknown_response_field.json

As per title, adding the `metadata` object on payment and mandates DTOs. 
I'm deliberately not setting any size validation on the map, problem details errors will provide the required context in case of failures. Moreover, we don't have anything to do if the same validation will change in future on our Payments v3 API

[JSDK-64] `metadata` object on payments and mandates DTOs

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/AuthorizationFlowAuthorizing.java
src/main/java/com/truelayer/java/payments/entities/AuthorizationFlowResponse.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/java/com/truelayer/java/payments/entities/AuthorizationFlowResponseTests.java
src/test/resources/__files/payments/200.start_authorization_flow.failed.json

Payments API has removed the `authorization_flow` object from the `POST /payments/{id}/authorization-flow` [response](https://docs.truelayer.com/reference/start-payment-authorization-flow), when `status=failed`.
Thus we are deprecating `AuthorizationFlowResponse.getAuthorizationFlow()` in favor of `AuthorizationFlowResponse.asAuthorizing().getAuthorizationFlow()`.
This change is not a bug fix neither a new feature. This is a change whereas the usage of the usage of library gets closer to the usage of the API.

[PAYG-920] remove auth flow from authorizing

---

CONTRIBUTING.md
gradle.properties
src/main/java/com/truelayer/java/mandates/IMandatesApi.java
src/main/java/com/truelayer/java/mandates/IMandatesHandler.java
src/main/java/com/truelayer/java/mandates/MandatesHandler.java
src/main/java/com/truelayer/java/mandates/entities/GetConfirmationOfFundsResponse.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/integration/MandatesIntegrationTests.java
src/test/java/com/truelayer/java/mandates/MandatesHandlerTests.java
src/test/resources/__files/mandates/200.get_confirmation_of_funds.json

This adds support for performing a Confirmation of Funds call on a mandate. The call requires requires a mandate id, an amount and a currency and returns a boolean and a time the check was performed. 

[JSDK-80] Confirmation of Funds

---

gradle.properties
src/main/java/com/truelayer/java/entities/beneficiary/MerchantAccount.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/resources/__files/payments/200.get_payment_by_id.authorization_required.json
src/test/resources/__files/payments/200.get_payment_by_id.authorized.json
src/test/resources/__files/payments/200.get_payment_by_id.authorizing.json
src/test/resources/__files/payments/200.get_payment_by_id.executed.json
src/test/resources/__files/payments/200.get_payment_by_id.failed.json
src/test/resources/__files/payments/200.get_payment_by_id.settled.json

Adds support for the `reference` field when creating single payments towards merchant account. 

[REC-631] reference added to payments into merchant accounts

---

gradle.properties
src/main/java/com/truelayer/java/entities/Address.java
src/main/java/com/truelayer/java/entities/User.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/resources/__files/payments/200.get_payment_by_id.authorization_required.json

Adding the `date_of_birth` and `address` fields to the `user` object.
[Fixes # (PAYG-1133)]

[PAYG-1133] Add extra fields to user object

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/CreatePaymentResponse.java
src/main/java/com/truelayer/java/payments/entities/CreatePaymentResponseAuthorizationRequired.java
src/main/java/com/truelayer/java/payments/entities/CreatePaymentResponseAuthorized.java
src/main/java/com/truelayer/java/payments/entities/CreatePaymentResponseFailed.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/java/com/truelayer/java/integration/PaymentsIntegrationTests.java
src/test/java/com/truelayer/java/integration/cache/DefaultAccessTokenCacheTests.java
src/test/java/com/truelayer/java/integration/cache/NoAccessTokenCacheTests.java
src/test/java/com/truelayer/java/payments/entities/CreatePaymentResponseTests.java
src/test/resources/__files/payments/201.create_payment.authorization_required.json
src/test/resources/__files/payments/201.create_payment.authorized.json
src/test/resources/__files/payments/201.create_payment.failed.json

Adds different statuses to the create payment response.

feat: [PAYG-1169] add status to create payment response

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/paymentdetail/AuthorizationFlowAction.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/Form.java
src/test/resources/__files/payments/200.start_authorization_flow.authorizing.form.json

Fixes an issue with the `form` and `consent` action responses. Due to a missing annotation, they were not correctly deserialised as such. 
This PR constitudes a quick fix. However, we will need to implement more robust tests for deserialisation to avoid similar issues.

fix: `form` and `consent` action response deserialisation

---

gradle.properties
src/main/java/com/truelayer/java/http/OkHttpClientFactory.java
src/test/java/com/truelayer/java/http/OkHttpClientFactoryTests.java
src/test/java/com/truelayer/java/integration/TimeoutIntegrationTests.java

- New feature: a default value is set for read timeouts on our base HTTP client. The values is inline with our API ingress timeout. 
- Bugfix: This PR solves a bug in the existing custom timeout logic: before this, while setting a custom (call) timeout we did not reset the default values for _connect_, _write_ and _read_ timeout, coming with the OkHttp library. Before this release, a customer setting a custom value > 10s, could still hit one of the underlying connect/write/read timeouts at 10s.

[EWT-79] Default READ timeout reviewed + bugfix for existing custom timeout logic

---

gradle.properties
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/ExternalPayment.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/MerchantAccountPayment.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/PaymentSource.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/Payout.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/Refund.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/Remitter.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/Transaction.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/accountidentifier/AccountIdentifier.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/accountidentifier/IbanAccountIdentifier.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/accountidentifier/SortCodeAccountNumberAccountIdentifier.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/beneficiary/Beneficiary.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/beneficiary/BusinessAccount.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/beneficiary/ExternalAccount.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/beneficiary/PaymentSource.java
src/test/java/com/truelayer/java/acceptance/MerchantAccountsAcceptanceTests.java
src/test/java/com/truelayer/java/merchantaccounts/entities/transactions/TransactionTests.java
src/test/java/com/truelayer/java/merchantaccounts/entities/transactions/accountidentifier/AccountIdentifierTests.java
src/test/java/com/truelayer/java/merchantaccounts/entities/transactions/beneficiary/BeneficiaryTests.java
src/test/resources/__files/merchant_accounts/200.get_transactions.json

Fixes the existing response DTOs on the [transaction list endpoint](https://docs.truelayer.com/reference/merchant-account-get-transactions). Unfortunately some of the changes are breaking, thus the bump to version `6.0.0`.
Adds supports for refunds on the same endpoint. 

[EWT-85] fixes existing items returned by the `merchant-accounts/{id}/transactions` endpoint and add support for refunds

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/Constants.java
src/main/java/com/truelayer/java/payments/IPaymentsApi.java
src/test/java/com/truelayer/java/TestUtils.java
src/test/java/com/truelayer/java/integration/PaymentsIntegrationTests.java

Adds the possibility to specify the X-Forwarded-For header field on [Start authorisation flow API request](https://docs.truelayer.com/reference/start-payment-authorization-flow). 
Implements #194

[EWT-135] feat: adds support for `X-Forwarded-For` HTTP header in start auth flow for single payments

---

README.md
build.gradle
gradle.properties
src/main/java/com/truelayer/java/Constants.java
src/main/java/com/truelayer/java/entities/RelatedProducts.java
src/main/java/com/truelayer/java/http/entities/Headers.java
src/main/java/com/truelayer/java/http/mappers/HeadersMapper.java
src/main/java/com/truelayer/java/mandates/entities/CreateMandateRequest.java
src/main/java/com/truelayer/java/payments/entities/CreatePaymentRequest.java
src/test/java/com/truelayer/java/TestUtils.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/java/com/truelayer/java/http/mappers/HeadersMapperTests.java
src/test/java/com/truelayer/java/integration/MandatesIntegrationTests.java
src/test/java/com/truelayer/java/integration/PaymentsIntegrationTests.java

- feat(DNTT-461): Adds support for related_products when creating payments and mandates
- updated version
- feat(EWT-350): Adds support for X-Device-User-Agent HTTP header on Start authorization flow
- chores: dependencies and readme updates

[DNTT-165] Adds support for related_products object, X-Device-User-Agent

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/payments/entities/paymentdetail/ExecutedPaymentDetail.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/SettledPaymentDetail.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/SettlementRisk.java
src/test/java/com/truelayer/java/payments/entities/paymentdetail/PaymentDetailTests.java

- Adds the settlement_risk field on executed and settlements payment details types.
- Bumps OkHttp to latest version 
[Fixes #226]

[DNTT-489] Added settlement_risk to executed and settled payment details response types

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/paymentdetail/AuthorizedPaymentDetail.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/FailedPaymentDetail.java
src/test/java/com/truelayer/java/payments/entities/paymentdetail/PaymentDetailTests.java
src/test/resources/__files/payments/200.get_payment_by_id.bank_transfer.authorized.json
src/test/resources/__files/payments/200.get_payment_by_id.bank_transfer.failed.json

Add `payment_source` property to `Authorized` and `Failed` payment details as per [Get Payment reference docs](https://docs.truelayer.com/reference/get-payment-1)

[EWT-371] Add payment_source property to authorized and failed payment details

---

.github/workflows/acceptance-tests-on-forks.yml
build.gradle
src/test/java/com/truelayer/java/acceptance/PaymentsProvidersAcceptanceTests.java

As per the current CI setup, it's impossible to run acceptance tests on forks opened by individuals which are not TL collaborators. 
This new workflow should let TL contributors to manually trigger the acceptance tests only PRs that's trying to merge a forked branch into our repository. 
Inspired by [this article](https://michaelheap.com/access-secrets-from-forks/).

[EWT-361] new workflow to run acceptance tests on forks

---

README.md
build.gradle
gradle.properties
justfile
src/main/java/com/truelayer/java/Constants.java
src/main/java/com/truelayer/java/http/entities/Headers.java
src/main/java/com/truelayer/java/http/mappers/HeadersMapper.java
src/main/java/com/truelayer/java/merchantaccounts/IMerchantAccountsApi.java
src/main/java/com/truelayer/java/merchantaccounts/IMerchantAccountsHandler.java
src/main/java/com/truelayer/java/merchantaccounts/MerchantAccountsHandler.java
src/main/java/com/truelayer/java/merchantaccounts/entities/ListTransactionsQuery.java
src/main/java/com/truelayer/java/merchantaccounts/entities/ListTransactionsResponse.java
src/test/java/com/truelayer/java/TestUtils.java
src/test/java/com/truelayer/java/acceptance/MerchantAccountsAcceptanceTests.java
src/test/java/com/truelayer/java/integration/HttpHeadersManagementTests.java
src/test/java/com/truelayer/java/integration/MerchantAccountsIntegrationTests.java
src/test/java/com/truelayer/java/merchantaccounts/MerchantAccountsHandlerTests.java
src/test/resources/__files/merchant_accounts/200.get_transactions.json

Adds support for paginating merchant accounts transactions. 
If not enabled at their client setting already, clients created before December 2023 have to explicitly opt-in with the help of an HTTP header [as described on our public API documentation](https://docs.truelayer.com/docs/enable-pagination-transactions-endpoint#enable-pagination).
To do so, when using the Java library, those clients can use a new overload of the `listTransactions` API accepts an extra headers parameter:
```java
// Clients created before December 2023
tlClient.merchantAccounts()
.listTransactions(
Headers.builder()
.enablePagination() //required to opt-in for pagination
.build(), 
getMerchantAccount(CurrencyCode.GBP).getId(),
ListTransactionsQuery.builder().from(from).to(to).build())
.get();
```
Clients created …

feat(EWT-535): Support for merchant account transactions pagination

---

gradle.properties
src/main/java/com/truelayer/java/entities/ProviderAvailability.java
src/main/java/com/truelayer/java/paymentsproviders/entities/BankTransferCapabilities.java
src/main/java/com/truelayer/java/paymentsproviders/entities/VrpCommercialCapabilities.java
src/main/java/com/truelayer/java/paymentsproviders/entities/VrpSweepingCapabilities.java
src/test/resources/__files/payments/200.start_authorization_flow.authorizing.provider_selection.json
src/test/resources/__files/payments_providers/200.get_payments_provider.json

- Add `capabilities.payments.bankTransfer.availability` field to payments provider response entity 
- Add `capabilities.mandates.vrpSweeping.availability` field to payments provider response entity
- Add `capabilities.mandates.vrpCommercial.availability` field to payments provider response entity
- Update `ProviderAvailability` object removing `errorRate` field
Fixes [EWT-539](https://truelayer.atlassian.net/browse/EWT-539)
[EWT-539]: https://truelayer.atlassian.net/browse/EWT-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EWT-539] Update provider availability

---

gradle.properties
src/main/java/com/truelayer/java/payments/entities/paymentdetail/forminput/Input.java
src/test/resources/__files/payments/200.start_authorization_flow.authorizing.form.json

> [!WARNING]  
> This is a breaking change from the library perspective. 
Fixes a long time oversight: the description field in form actions objects was implemented as `String`, but it's of type `DisplayText`. 
Unfortunately this is a breaking change at compilation time.

fix(EWT-543): type change for description field in authorization flow actions objects

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/versioninfo/LibraryInfoLoader.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java

1. Raises settlement and authorisation timeouts in our acceptance tests to reduce pointless noise on our reporting channels
2. reviews implementation of the Version info loader class to remove the dependencies on the beanutils package
Fixes EWT-561 and EWT-390

Adjust settlement/authorisation timeouts in acceptance tests, and review version info loader implementation

---

gradle.properties
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java

In mandates acceptance tests, we have some testing scenario requiring us to wait and poll a mandate until it reaches a certain status, before proceeding with assertions and/or other operations. 
The method taking care of this polling operation was using by mistake the `tlClient` built in the base class, which uses default scopes: as a result, we were invoking the GET /mandates endpoint always using the `recurring_payments:sweeping` scope (the default if not set explicitly when building the client), and this was causing calls related to cVRP mandates to fail (a `recurring_payments:commercial` scope is expected in this case). 
This PR will fix the bug, that went unnoticed for some time until a stricter check on scopes had been introduced by PGW (PR …

[EWT-590] Fix mandates acceptance tests

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/entities/Configuration.java
src/main/java/com/truelayer/java/entities/Retry.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/AttemptFailedPaymentDetail.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/AuthorizationFlowAction.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/PaymentDetail.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/Retry.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/RetryOption.java
src/main/java/com/truelayer/java/payments/entities/paymentdetail/Status.java
src/main/java/com/truelayer/java/payments/entities/paymentmethod/BankTransfer.java
src/test/java/com/truelayer/java/TestUtils.java
src/test/java/com/truelayer/java/acceptance/MandatesAcceptanceTests.java
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java
src/test/java/com/truelayer/java/integration/PaymentsIntegrationTests.java
src/test/java/com/truelayer/java/payments/entities/paymentdetail/AuthorizationFlowActionTests.java
src/test/java/com/truelayer/java/payments/entities/paymentdetail/PaymentDetailTests.java
src/test/java/com/truelayer/java/payments/entities/paymentmethod/PaymentMethodTests.java
src/test/resources/__files/payments/200.get_payment_by_id.bank_transfer.attempt_failed.json

Add support for `retry` parameter:
- customers can opt in to retry feature initialising the `retry` property in the `CreatePayment.PaymentMethod.BankTransfer` object
- added support for new `AttemptFailed` payment details 
- added unit, integration and acceptance tests

[ACL-138] Add support for retry parameter

---

build.gradle
gradle.properties
src/test/java/com/truelayer/java/acceptance/PaymentsAcceptanceTests.java

When testing `attempt_failed` payment details scenario, poll payment status to avoid issues when there's a delay in consuming status update events

[ACL-174] Improve retry payments acceptance tests

---

gradle.properties
src/main/java/com/truelayer/java/entities/accountidentifier/BbanAccountIdentifier.java
src/main/java/com/truelayer/java/entities/accountidentifier/IbanAccountIdentifier.java
src/main/java/com/truelayer/java/entities/accountidentifier/NrbAccountIdentifier.java
src/main/java/com/truelayer/java/entities/accountidentifier/SortCodeAccountNumberAccountIdentifier.java
src/main/java/com/truelayer/java/mandates/entities/beneficiary/ExternalAccount.java
src/main/java/com/truelayer/java/mandates/entities/beneficiary/MerchantAccount.java
src/main/java/com/truelayer/java/mandates/entities/mandate/VRPCommercialMandate.java
src/main/java/com/truelayer/java/mandates/entities/mandate/VRPSweepingMandate.java
src/main/java/com/truelayer/java/payments/entities/beneficiary/ExternalAccount.java
src/main/java/com/truelayer/java/payments/entities/beneficiary/MerchantAccount.java
src/main/java/com/truelayer/java/payments/entities/paymentmethod/BankTransfer.java
src/main/java/com/truelayer/java/payments/entities/paymentmethod/Mandate.java
src/main/java/com/truelayer/java/payments/entities/providerselection/PreselectedProviderSelection.java
src/main/java/com/truelayer/java/payments/entities/providerselection/UserSelectedProviderSelection.java
src/main/java/com/truelayer/java/payments/entities/schemeselection/InstantOnlySchemeSelection.java
src/main/java/com/truelayer/java/payments/entities/schemeselection/InstantPreferredSchemeSelection.java
src/main/java/com/truelayer/java/payments/entities/schemeselection/SchemeSelection.java
src/test/java/com/truelayer/java/acceptance/PaymentsProvidersAcceptanceTests.java
src/test/java/com/truelayer/java/integration/PaymentsIntegrationTests.java
src/test/java/com/truelayer/java/payments/entities/SchemeSelectionTests.java
src/test/java/com/truelayer/java/payments/entities/paymentmethod/PaymentMethodTests.java

- Add missing `EqualsAndHashCode` lombok annotations on `PaymentMethod` subclasses and related properties
- Add unit tests

[ACL-175] Fix missing EqualsAndHashCode Lombok annotations

---

gradle.properties
src/main/java/com/truelayer/java/payouts/entities/CreatePayoutRequest.java
src/main/java/com/truelayer/java/payouts/entities/submerchants/BusinessClient.java
src/main/java/com/truelayer/java/payouts/entities/submerchants/SubMerchants.java
src/main/java/com/truelayer/java/payouts/entities/submerchants/UltimateCounterparty.java
src/test/java/com/truelayer/java/acceptance/PayoutsAcceptanceTests.java
src/test/java/com/truelayer/java/payouts/entities/submerchants/UltimateCounterpartyTests.java

Add `sub_merchants` property to `CreatePayoutRequest`

[ACL-167] Add sub_merchants support to payouts

---

build.gradle
gradle.properties
src/main/java/com/truelayer/java/merchantaccounts/entities/UpdateSweepingRequest.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/MerchantAccountPayment.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/Payout.java
src/main/java/com/truelayer/java/merchantaccounts/entities/transactions/Refund.java
src/test/java/com/truelayer/java/acceptance/MerchantAccountsAcceptanceTests.java
src/test/java/com/truelayer/java/integration/MerchantAccountsIntegrationTests.java
src/test/java/com/truelayer/java/merchantaccounts/MerchantAccountsHandlerTests.java
src/test/java/com/truelayer/java/merchantaccounts/entities/transactions/TransactionTests.java

- **removed currency from merchant account update sweeping request**
- **add metadata to merchant account transactions**
- **update version**
This PR is related to the following Jira tickets:
- [ACL-186](https://truelayer.atlassian.net/browse/ACL-186)
- [ACL-214](https://truelayer.atlassian.net/browse/ACL-214)
- add `metadata` optional property to merchant account transactions (refunds, payouts and merchant account payments)
- ⚠️  **breaking**: removed `currency` from update sweeping request
[ACL-186]: https://truelayer.atlassian.net/browse/ACL-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ACL-214]: https://truelayer.atlassian.net/browse/ACL-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

Merchant accounts updates

---

.github/pull_request_template.md
build.gradle
gradle.properties
src/main/java/com/truelayer/java/signupplus/ISignupPlusApi.java
src/main/java/com/truelayer/java/signupplus/ISignupPlusHandler.java
src/main/java/com/truelayer/java/signupplus/SignupPlusHandler.java
src/main/java/com/truelayer/java/signupplus/entities/GenerateAuthUriRequest.java
src/main/java/com/truelayer/java/signupplus/entities/GenerateAuthUriResponse.java
src/test/java/com/truelayer/java/acceptance/SignupPlusAcceptanceTests.java
src/test/java/com/truelayer/java/integration/SignupPlusIntegrationTests.java
src/test/java/com/truelayer/java/signupplus/SignupPlusHandlerTests.java
src/test/resources/__files/signup_plus/200.generate_auth_uri.json

I've realised that in #322 I've forgotten adding the support for this auth URI generation endpoint 😞 .
This PR really adds that.

feat(ACL-251): Adds method to generate SU+ Authentication URI for FI payments

---

.github/workflows/release-snapshot.yml
.github/workflows/workflow-branch.yml
.github/workflows/workflow-main.yml
.github/workflows/workflow-pr-fork.yml
README.md
build.gradle
examples/quarkus-mvc/build.gradle
examples/quarkus-mvc/src/main/java/com/truelayer/quarkusmvc/services/DonationService.java
gradle.properties

This PR migrates the publishing pipeline from Bintray/JCenter to Maven Central using the vanniktech gradle-maven-publish-plugin and resolves the 403 errors we were experiencing with the previous publishing setup.
The Nexus Repository Manager v2 and dependent services, including OSSRH, [reached end-of-life on June 30, 2025.](https://central.sonatype.org/pages/ossrh-eol/) This necessitated the migration to either a newer version of Nexus Sonatype(v3) or to Maven Central for our publishing pipeline. 
Considering that: 
- We don't really take advantage of Nexus Sonatype at the minute, but we have been using it just as proxy to Maven central
- When we originally set up the release pipeline, we would have considered publishing directly to Maven Central, but at the time, the only way to automate …

[ACL-296] Move publishing to Maven Central
